spring:
  http:
    encoding.charset: UTF-8
    encoding.force: true
  datasource:
    name: ykttest
    url: jdbc:mysql://192.168.100.29:3306/qdappdev?useUnicode=true&&characterEncoding=utf-8&useSSL=false
    username: qdappdev
    password: qdappdev
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 3
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      filters: stat,wall,log4j
  jpa:
    database: mysql
    show-sql: true
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: null
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000