spring:
  http:
    encoding.charset: UTF-8
    encoding.force: true
  datasource:
    name: yct
    url: jdbc:mysql://47.105.102.121:3306/ykt?useUnicode=true&&characterEncoding=utf-8&useSSL=false
    username: root
    password: actorYKT
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 3
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      filters: stat,wall,log4j
  redis:
    database: 0
    host: 47.105.102.121
    port: 6379
    password: actorYKTRedis
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        max-wait: -1
        min-idle: 0
    timeout: 1000